name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: go
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['1.18', '1.19']
    steps:
      - name: setup
        uses: actions/setup-go@v4
        with:
          go-version: ${{matrix.go}}

      - name: checkout
        uses: actions/checkout@v3

      - name: test
        run: make
